name: retrofit_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^3.3.1
  get_it: ^7.2.0
  injectable: ^1.5.4
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2
  injectable_generator: ^1.5.5
  json_serializable: ^6.5.4
  

flutter:
  uses-material-design: true